/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "oqhlzmdmtkvgfpulyqjw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xaGx6bWRtdGt2Z2ZwdWx5cWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODE2MDUsImV4cCI6MjA3MzM1NzYwNX0.gah4t_pcHT-t7FFlgiaGNGHU-5YeQ6qClU9g-1ZWqLo"